
services:
  # PostgreSQL Database
  database:
    image: postgres:17-alpine
    container_name: wealthe-db-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: wealthe_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wealthe_password
      PGDATA: /var/lib/postgresql/data/pgdata_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      #- ./db/sql_final:/docker-entrypoint-initdb.d:ro #this schema and data should be loaded in db inside container
      - ./backupV20.dump:/docker-entrypoint-initdb.d/backup.dump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    ports:
      - "5401:5432"
    networks:
      - wealthe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wealthe_db_test"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


networks:
  wealthe-network:
    driver: bridge
    name: wealthe-network-1

volumes:
  postgres_data_test:
    driver: local
    name: wealthe-postgres-data-test

